generate:
  dataset: 'small_arena'  # Name of original dataset folder
  compress: False         # Compress original graph (Remove degree 2 nodes?)
  num_charges: 8          # Maximum storage of charges
  max_charge: 1           # Charge usage for maximum distance
  p_travel: 0.9           # Probability to travel to correct neighbor
  num_chargers: 2         # Number of random chargers on the map

evaluate:
  alpha: 0.95             # Discount factor for value iteration
  error_min: 0.001        # Error at which to break greedy algorithm
  num_blocks: 100         # Number of blocks to split statespace in

test:
  static_test: True       # Static or stochastic test of aquired policy
  start_charge: 7         # Charge of state to test policy with
  start_node: 14           # Start node of state to test policy with
  target_node: 32         # Target node of state to test policy with
  max_iter: 200           # Maximum tries before stopping policy iteration
